version: '3.9'
services:
  agent:
    image: "datadog/agent:7.30.0"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=truhe
      - DD_TAGS='env:development'
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    labels:
      com.datadoghq.ad.logs: '[{"source": "agent", "service": "agent"}]'
  leaky_cache:
    build:
      context: leaky
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=8080
      - DD_SERVICE=leaky-cache-python-service
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_VERSION=1.0
    ports:
      - "8080:8080"
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "leaky-cache-python-service"}]'
  leaky_c_extension:
    build:
      context: c_extension
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=8081
      - DD_SERVICE=leaky-c-extension-python-service
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_VERSION=1.0
    ports:
      - "8081:8081"
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "leaky-c-extension-python-service"}]'
  well_behaved:
    build:
      context: well_behaved
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=8082
      - DD_SERVICE=well-behaved-python-service
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_VERSION=1.0
    ports:
      - "8082:8082"
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "well-behaved-python-service"}]'
  leaky_cache_service_client:
    build:
      context: client
    environment:
      - API_HOST=leaky_cache
      - API_PORT=8080
    depends_on:
      - leaky
  c_extension_service_client:
    build:
      context: client
    environment:
      - API_HOST=leaky_c_extension
      - API_PORT=8081
  well_behaved_service_client:
    build:
      context: client
    environment:
      - API_HOST=well_behaved
      - API_PORT=8082
    depends_on:
      - well_behaved