version: '3.8'
services:
  agent:
    image: datadog/agent:7.30.0
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS='env:development'
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    labels:
      com.datadoghq.ad.logs: '[{"source": "agent", "service": "agent"}]'
  leaky_service:
    build:
      context: leaky
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - DD_AGENT_HOST=agent
      - DD_ENV=development
      - DD_SERVICE=leaky-python-app
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_VERSION=1.0
    ports:
      - "5001:5001"
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "leaky-service"}]'
  leaky_service_client:
    build:
      context: client
    environment:
      - API_HOST=leaky_service
      - API_PORT=5001
    links:
      - leaky_service
    depends_on:
      - leaky_service