version: '3.9'
services:
  agent:
    image: "datadog/agent:7.30.0"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS='env:development'
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    labels:
      com.datadoghq.ad.logs: '[{"source": "agent", "service": "agent"}]'
  cache_app_version_0_1_0:
    container_name: cache-app-v0.1.0
    build:
      context: v0.1.0
    environment:
      - STAGGER_SECONDS=1
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=8080
      - CACHE_MAX_ITEMS=1000
      - CACHE_MAX_AGE_SECS=60
      - DD_SERVICE=cache-app-v0.1.0
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_PROFILING_HEAP_ENABLED=true
      - DD_VERSION=0.1.0
    ports:
      - "8080:8080"
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "cache-app-v0.1.0"}]'
  cache_app_version_0_1_1:
    container_name: cache-app-v0.1.1
    build:
      context: v0.1.1
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=8081
      - CACHE_MAX_ITEMS=1000
      - CACHE_MAX_AGE_SECS=60
      - DD_SERVICE=cache-app-v0.1.1
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_PROFILING_ENABLED=true
      - DD_PROFILING_HEAP_ENABLED=true
      - DD_VERSION=0.1.1
    ports:
      - "8081:8081"
    depends_on:
      - agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "cache-app-v0.1.1"}]'
  v0_1_0_cache_service_client:
    build:
      context: client
    deploy:
      replicas: 10
    environment:
      - API_HOST=cache_app_version_0_1_0
      - API_PORT=8080
      - PAYLOAD_SIZE=10000
    depends_on:
      - cache_app_version_0_1_0
  v0_1_1_cache_service_client:
    build:
      context: client
    deploy:
      replicas: 10
    environment:
      - API_HOST=cache_app_version_0_1_1
      - API_PORT=8081
      - PAYLOAD_SIZE=10000
    depends_on:
      - cache_app_version_0_1_1
